dist: trusty
language: go

go:
  - 1.8

install:
  - sudo apt-get install intltool gperf libudev-dev
  - wget https://github.com/libusb/libusb/archive/v1.0.20.tar.gz
  - tar xvzf v1.0.20.tar.gz
  - pushd libusb-1.0.20
  - ./autogen.sh && ./configure && make && sudo make install
  - popd
  - wget https://github.com/libusb/libusb-compat-0.1/archive/v0.1.5.tar.gz
  - tar xvzf v0.1.5.tar.gz
  - pushd libusb-compat-0.1-0.1.5
  - ./autogen.sh && ./configure && make && sudo make install
  - popd
  - wget https://github.com/google/protobuf/archive/v3.3.0.tar.gz
  - tar -xzvf v3.3.0.tar.gz
  - pushd protobuf-3.3.0
  - ./autogen.sh && ./configure --prefix=/usr && make && sudo make install
  - popd
  - rm -rf protobuf-3.3.0 libusb-compat-0.1-0.1.5 libusb-1.0.20
  - go get -u github.com/Masterminds/glide
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/golang/lint/golint
  - glide install

script: 
  - touch .env
  - make lint
  - make
  - ./auto/travis/test.sh
  - go vet $(go list ./... | grep -vi 'vendor\|testing')
