dist: trusty
language: go

go:
  - 1.8

install:
  - sudo apt-get install intltool gperf libudev-dev
  - wget https://github.com/libusb/libusb/archive/v1.0.20.tar.gz
  - tar xvzf v1.0.20.tar.gz
  - pushd libusb-1.0.20
  - ./autogen.sh && ./configure && make && sudo make install
  - popd
  - wget https://github.com/libusb/libusb-compat-0.1/archive/v0.1.5.tar.gz
  - tar xvzf v0.1.5.tar.gz
  - pushd libusb-compat-0.1-0.1.5
  - ./autogen.sh && ./configure && make && sudo make install
  - popd
  - sudo apt-get install unzip
  - wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
  - sudo unzip protoc-3.3.0-linux-x86_64.zip -d /usr/local/protoc-3.3.0
  - export PATH=${PATH}:/usr/local/protoc-3.3.0/bin
  - protoc --version
  - rm -rf protobuf-3.3.0 libusb-compat-0.1-0.1.5 libusb-1.0.20

script: 
  - touch .env
  - make
  - make test
